### ISSUE TITLE
tin --sync

### ISSUE THREAD

**Issue by tmcw** [jprichardson/tin#14]
Would read each package type, and update the rest automatically, sorting package specs by mtime and availability. Would be useful for npm packages that decide to walk on the bower wild side.

**Comment by jprichardson** [comment]
PRs welcome ;)

**Comment by jprichardson** [comment]
Hey Tom, now that npm is actively promoting and pushing to be a package manager for the browser as well, do you think that there is still value in using bower over npm? Or do you think that npm still has this server-side stigma still attached to it?

**Comment by tmcw** [comment]
I've never been in favor of using bower over npm - npm+browserify has been a better solution from day one :) For a few popular packages, enough people ask for bower that I figure it's worth supporting, but I'm doing so less and less and more just advising that if people really insist on using bower, they install from the github url rather than a bower package.

**Comment by tmcw** [comment]
Closing because of no response for several months. Feel free to reopen if this issue will be fixed.
