### ISSUE TITLE
Auto-create all 3 files with some subcommand

### ISSUE THREAD

**Issue by paulmillr** [jprichardson/tin#4]
How about `tin --create`. Would be super useful.

Mind if I do a pull req @jprichardson ?

**Comment by jprichardson** [comment]
That would be useful! Go for it.

On Monday, October 28, 2013, Paul Miller wrote:

> How about tin --create. Would be super useful.
> 
> Mind if I do a pull req @jprichardson https://github.com/jprichardson ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jprichardson/tin/issues/4
> .

## 

Follow me on Twitter: http://twitter.com/jprichardson
